.PHONY: day1 day2 day3 day4 day5 day6 all

day1:
	./day1_boot_guard.sh
day2:
	./day2_k6_suite.sh
day3:
	./day3_security_scan.sh
day4:
	@echo "Copie ops/day4_monitoring_alerts.yml dans la conf Prometheus Alertmanager."
day5:
	./day5_qa_final.sh
day6:
	./day6_release.sh

all: day1 day2 day3 day4 day5 day6